/**
 * City metadata — Facebook pages, nearby cities, region groupings.
 * Extend as cities grow.
 */

export type CityMeta = {
  slug: string
  facebook?: string        // official city/community Facebook page
  region?: string          // NE Alabama, Central Alabama, etc.
  nearbySlug?: string[]    // adjacent cities for internal SEO links
  population?: number
  tagline?: string         // one-line for meta/display
  heroImage?: string       // path under /public, e.g. /images/locations/anniston-hero.webp
  heroCredit?: string      // visible photo credit for the hero
}

export const CITY_META: CityMeta[] = [
  {
    slug: "anniston",
    facebook: "https://www.facebook.com/CityofAnniston",
    region: "NE Alabama",
    nearbySlug: ["oxford", "jacksonville", "gadsden", "talladega"],
    population: 22000,
    tagline: "The Model City of the New South",
    heroImage: "/images/locations/anniston-hero.webp",
    heroCredit: "Photo: Art Meripol, Alabama Tourism Department",
  },
  {
    slug: "oxford",
    facebook: "https://www.facebook.com/OxfordAlabama",
    region: "NE Alabama",
    nearbySlug: ["anniston", "jacksonville", "talladega"],
    population: 22000,
    tagline: "Calhoun County's commercial spine — the city the highway built",
    heroImage: "/images/locations/oxford-hero.webp",
  },
  {
    slug: "jacksonville",
    facebook: "https://www.facebook.com/JacksonvilleAL",
    region: "NE Alabama",
    nearbySlug: ["anniston", "oxford", "gadsden", "piedmont"],
    population: 12000,
    tagline: "The town that taught people to sing — and kept some of them",
    heroImage: "/images/locations/jacksonville-hero.webp",
  },
  {
    slug: "gadsden",
    facebook: "https://www.facebook.com/gadsdencity",
    region: "NE Alabama",
    nearbySlug: ["anniston", "jacksonville", "attalla", "albertville"],
    population: 33000,
    tagline: "The city on the Coosa — where the falls were falling before anyone named them",
    heroImage: "/images/locations/gadsden-hero.webp",
  },
  {
    slug: "talladega",
    facebook: "https://www.facebook.com/CityofTalladega",
    region: "NE Alabama",
    nearbySlug: ["anniston", "oxford", "sylacauga"],
    population: 15000,
    tagline: "The Amistad Murals are here. So is the track. Both matter.",
    heroImage: "/images/locations/talladega-hero.webp",
  },
  {
    slug: "centre",
    region: "NE Alabama",
    nearbySlug: ["gadsden", "attalla"],
    population: 3500,
    tagline: "Cherokee County seat — named for a people, sitting on their river",
    heroImage: "/images/locations/centre-hero.webp",
  },
  {
    slug: "piedmont",
    facebook: "https://www.facebook.com/CityofPiedmontAlabama",
    region: "NE Alabama",
    nearbySlug: ["jacksonville", "anniston", "cedartown"],
    population: 5000,
    tagline: "At the foot of Cheaha — where seventh graders take the stage and teach you something",
    heroImage: "/images/locations/piedmont-hero.webp",
  },
  {
    slug: "attalla",
    facebook: "https://www.facebook.com/CityofAttalla",
    region: "NE Alabama",
    nearbySlug: ["gadsden", "albertville"],
    population: 5500,
    tagline: "Where the Coosa Valley meets the sand mountain ridge",
    heroImage: "/images/locations/attalla-hero.webp",
  },
  {
    slug: "albertville",
    facebook: "https://www.facebook.com/AlbertvilleAL",
    region: "NE Alabama",
    nearbySlug: ["gadsden", "boaz", "guntersville"],
    population: 22000,
  },
  {
    slug: "birmingham",
    facebook: "https://www.facebook.com/BirminghamAL",
    region: "Central Alabama",
    nearbySlug: ["hoover", "vestavia-hills", "trussville", "gardendale"],
    population: 212000,
    tagline: "The Magic City",
    heroImage: "/images/locations/birmingham-hero.webp",
  },
  {
    slug: "huntsville",
    facebook: "https://www.facebook.com/HuntsvilleAL",
    region: "North Alabama",
    nearbySlug: ["madison", "decatur", "athens"],
    population: 200000,
    tagline: "The Rocket City",
    heroImage: "/images/locations/huntsville-hero.webp",
  },
  {
    slug: "montgomery",
    facebook: "https://www.facebook.com/CityofMontgomery",
    region: "Central Alabama",
    nearbySlug: ["prattville", "millbrook", "wetumpka"],
    population: 197000,
    tagline: "The Cradle of the Confederacy and the Civil Rights Movement",
    heroImage: "/images/locations/montgomery-hero.webp",
  },
  {
    slug: "tuscaloosa",
    facebook: "https://www.facebook.com/CityofTuscaloosa",
    region: "West Alabama",
    nearbySlug: ["northport", "cottondale"],
    population: 100000,
    tagline: "Home of the University of Alabama",
    heroImage: "/images/locations/tuscaloosa-hero.webp",
  },
  {
    slug: "mobile",
    facebook: "https://www.facebook.com/CityofMobile",
    region: "South Alabama",
    nearbySlug: ["prichard", "saraland", "daphne"],
    population: 187000,
    tagline: "The Port City",
  },
  {
    slug: "decatur",
    facebook: "https://www.facebook.com/CityofDecatur",
    region: "North Alabama",
    nearbySlug: ["huntsville", "hartselle", "athens"],
    population: 53000,
  },
  {
    slug: "florence",
    facebook: "https://www.facebook.com/CityofFlorenceAL",
    region: "North Alabama",
    nearbySlug: ["muscle-shoals", "sheffield", "tuscumbia"],
    population: 42000,
    tagline: "The Shoals",
    heroImage: "/images/locations/florence-hero.webp",
  },
  {
    slug: "adamsville",
    region: "Alabama",
    tagline: "Adamsville, Alabama",
    heroImage: "/images/locations/adamsville-hero.webp",
  },
  {
    slug: "alabaster",
    region: "Alabama",
    tagline: "Alabaster, Alabama",
    heroImage: "/images/locations/alabaster-hero.webp",
  },
  {
    slug: "ardmore",
    region: "Alabama",
    tagline: "Ardmore, Alabama",
    heroImage: "/images/locations/ardmore-hero.webp",
  },
  {
    slug: "athens",
    region: "Alabama",
    tagline: "Athens, Alabama",
    heroImage: "/images/locations/athens-hero.webp",
  },
  {
    slug: "atlanta",
    region: "Alabama",
    tagline: "Atlanta, Alabama",
    heroImage: "/images/locations/atlanta-hero.webp",
  },
  {
    slug: "autaugaville",
    region: "Alabama",
    tagline: "Autaugaville, Alabama",
    heroImage: "/images/locations/autaugaville-hero.webp",
  },
  {
    slug: "alexandria",
    region: "Alabama",
    tagline: "Alexandria, Alabama",
    heroImage: "/images/locations/alexandria-hero.webp",
  },
  {
    slug: "altoona",
    region: "Alabama",
    tagline: "Altoona, Alabama",
    heroImage: "/images/locations/altoona-hero.webp",
  },
  {
    slug: "arab",
    region: "Alabama",
    tagline: "Arab, Alabama",
    heroImage: "/images/locations/arab-hero.webp",
  },
  {
    slug: "axis",
    region: "Alabama",
    tagline: "Axis, Alabama",
    heroImage: "/images/locations/axis-hero.webp",
  },
  {
    slug: "belle-mina",
    region: "Alabama",
    tagline: "Belle Mina, Alabama",
    heroImage: "/images/locations/belle-mina-hero.webp",
  },
  {
    slug: "ashford",
    region: "Alabama",
    tagline: "Ashford, Alabama",
    heroImage: "/images/locations/ashford-hero.webp",
  },
  {
    slug: "ashville",
    region: "Alabama",
    tagline: "Ashville, Alabama",
    heroImage: "/images/locations/ashville-hero.webp",
  },
  {
    slug: "auburn",
    region: "Alabama",
    tagline: "Auburn, Alabama",
    heroImage: "/images/locations/auburn-hero.webp",
  },
  {
    slug: "bay-minette",
    region: "Alabama",
    tagline: "Bay Minette, Alabama",
    heroImage: "/images/locations/bay-minette-hero.webp",
  },
  {
    slug: "bayou-la-batre",
    region: "Alabama",
    tagline: "Bayou La Batre, Alabama",
    heroImage: "/images/locations/bayou-la-batre-hero.webp",
  },
  {
    slug: "berry",
    region: "Alabama",
    tagline: "Berry, Alabama",
    heroImage: "/images/locations/berry-hero.webp",
  },
  {
    slug: "boaz",
    region: "Alabama",
    tagline: "Boaz, Alabama",
    heroImage: "/images/locations/boaz-hero.webp",
  },
  {
    slug: "brighton",
    region: "Alabama",
    tagline: "Brighton, Alabama",
    heroImage: "/images/locations/brighton-hero.webp",
  },
  {
    slug: "brookwood",
    region: "Alabama",
    tagline: "Brookwood, Alabama",
    heroImage: "/images/locations/brookwood-hero.webp",
  },
  {
    slug: "brownsboro",
    region: "Alabama",
    tagline: "Brownsboro, Alabama",
    heroImage: "/images/locations/brownsboro-hero.webp",
  },
  {
    slug: "burkville",
    region: "Alabama",
    tagline: "Burkville, Alabama",
    heroImage: "/images/locations/burkville-hero.webp",
  },
  {
    slug: "calera",
    region: "Alabama",
    tagline: "Calera, Alabama",
    heroImage: "/images/locations/calera-hero.webp",
  },
  {
    slug: "camp-hill",
    region: "Alabama",
    tagline: "Camp Hill, Alabama",
    heroImage: "/images/locations/camp-hill-hero.webp",
  },
  {
    slug: "cecil",
    region: "Alabama",
    tagline: "Cecil, Alabama",
    heroImage: "/images/locations/cecil-hero.webp",
  },
  {
    slug: "center-point",
    region: "Alabama",
    tagline: "Center Point, Alabama",
    heroImage: "/images/locations/center-point-hero.webp",
  },
  {
    slug: "chelsea",
    region: "Alabama",
    tagline: "Chelsea, Alabama",
    heroImage: "/images/locations/chelsea-hero.webp",
  },
  {
    slug: "childersburg",
    region: "Alabama",
    tagline: "Childersburg, Alabama",
    heroImage: "/images/locations/childersburg-hero.webp",
  },
  {
    slug: "chunchula",
    region: "Alabama",
    tagline: "Chunchula, Alabama",
    heroImage: "/images/locations/chunchula-hero.webp",
  },
  {
    slug: "clanton",
    region: "Alabama",
    tagline: "Clanton, Alabama",
    heroImage: "/images/locations/clanton-hero.webp",
  },
  {
    slug: "coaling",
    region: "Alabama",
    tagline: "Coaling, Alabama",
    heroImage: "/images/locations/coaling-hero.webp",
  },
  {
    slug: "coden",
    region: "Alabama",
    tagline: "Coden, Alabama",
    heroImage: "/images/locations/coden-hero.webp",
  },
  {
    slug: "coker",
    region: "Alabama",
    tagline: "Coker, Alabama",
    heroImage: "/images/locations/coker-hero.webp",
  },
  {
    slug: "columbia",
    region: "Alabama",
    tagline: "Columbia, Alabama",
    heroImage: "/images/locations/columbia-hero.webp",
  },
  {
    slug: "columbiana",
    region: "Alabama",
    tagline: "Columbiana, Alabama",
    heroImage: "/images/locations/columbiana-hero.webp",
  },
  {
    slug: "coosada",
    region: "Alabama",
    tagline: "Coosada, Alabama",
    heroImage: "/images/locations/coosada-hero.webp",
  },
  {
    slug: "cordova",
    region: "Alabama",
    tagline: "Cordova, Alabama",
    heroImage: "/images/locations/cordova-hero.webp",
  },
  {
    slug: "cottonwood",
    region: "Alabama",
    tagline: "Cottonwood, Alabama",
    heroImage: "/images/locations/cottonwood-hero.webp",
  },
  {
    slug: "cowarts",
    region: "Alabama",
    tagline: "Cowarts, Alabama",
    heroImage: "/images/locations/cowarts-hero.webp",
  },
  {
    slug: "creola",
    region: "Alabama",
    tagline: "Creola, Alabama",
    heroImage: "/images/locations/creola-hero.webp",
  },
  {
    slug: "daphne",
    region: "Alabama",
    tagline: "Daphne, Alabama",
    heroImage: "/images/locations/daphne-hero.webp",
  },
  {
    slug: "deatsville",
    region: "Alabama",
    tagline: "Deatsville, Alabama",
    heroImage: "/images/locations/deatsville-hero.webp",
  },
  {
    slug: "delta",
    region: "Alabama",
    tagline: "Delta, Alabama",
    heroImage: "/images/locations/delta-hero.webp",
  },
  {
    slug: "dora",
    region: "Alabama",
    tagline: "Dora, Alabama",
    heroImage: "/images/locations/dora-hero.webp",
  },
  {
    slug: "dothan",
    region: "Alabama",
    tagline: "Dothan, Alabama",
    heroImage: "/images/locations/dothan-hero.webp",
  },
  {
    slug: "duncanville",
    region: "Alabama",
    tagline: "Duncanville, Alabama",
    heroImage: "/images/locations/duncanville-hero.webp",
  },
  {
    slug: "eclectic",
    region: "Alabama",
    tagline: "Eclectic, Alabama",
    heroImage: "/images/locations/eclectic-hero.webp",
  },
  {
    slug: "elkmont",
    region: "Alabama",
    tagline: "Elkmont, Alabama",
    heroImage: "/images/locations/elkmont-hero.webp",
  },
  {
    slug: "elmore",
    region: "Alabama",
    tagline: "Elmore, Alabama",
    heroImage: "/images/locations/elmore-hero.webp",
  },
  {
    slug: "empire",
    region: "Alabama",
    tagline: "Empire, Alabama",
    heroImage: "/images/locations/empire-hero.webp",
  },
  {
    slug: "eutaw",
    region: "Alabama",
    tagline: "Eutaw, Alabama",
    heroImage: "/images/locations/eutaw-hero.webp",
  },
  {
    slug: "fairhope",
    region: "Alabama",
    tagline: "Fairhope, Alabama",
    heroImage: "/images/locations/fairhope-hero.webp",
  },
  {
    slug: "forestdale",
    region: "Alabama",
    tagline: "Forestdale, Alabama",
    heroImage: "/images/locations/forestdale-hero.webp",
  },
  {
    slug: "fultondale",
    region: "Alabama",
    tagline: "Fultondale, Alabama",
    heroImage: "/images/locations/fultondale-hero.webp",
  },
  {
    slug: "gallant",
    region: "Alabama",
    tagline: "Gallant, Alabama",
    heroImage: "/images/locations/gallant-hero.webp",
  },
  {
    slug: "glencoe",
    region: "Alabama",
    tagline: "Glencoe, Alabama",
    heroImage: "/images/locations/glencoe-hero.webp",
  },
  {
    slug: "gordo",
    region: "Alabama",
    tagline: "Gordo, Alabama",
    heroImage: "/images/locations/gordo-hero.webp",
  },
  {
    slug: "gordon",
    region: "Alabama",
    tagline: "Gordon, Alabama",
    heroImage: "/images/locations/gordon-hero.webp",
  },
  {
    slug: "grady",
    region: "Alabama",
    tagline: "Grady, Alabama",
    heroImage: "/images/locations/grady-hero.webp",
  },
  {
    slug: "grand-bay",
    region: "Alabama",
    tagline: "Grand Bay, Alabama",
    heroImage: "/images/locations/grand-bay-hero.webp",
  },
  {
    slug: "grant",
    region: "Alabama",
    tagline: "Grant, Alabama",
    heroImage: "/images/locations/grant-hero.webp",
  },
  {
    slug: "graysville",
    region: "Alabama",
    tagline: "Graysville, Alabama",
    heroImage: "/images/locations/graysville-hero.webp",
  },
  {
    slug: "gulf-shores",
    region: "Alabama",
    tagline: "Gulf Shores, Alabama",
    heroImage: "/images/locations/gulf-shores-hero.webp",
  },
  {
    slug: "guntersville",
    region: "Alabama",
    tagline: "Guntersville, Alabama",
    heroImage: "/images/locations/guntersville-hero.webp",
  },
  {
    slug: "gurley",
    region: "Alabama",
    tagline: "Gurley, Alabama",
    heroImage: "/images/locations/gurley-hero.webp",
  },
  {
    slug: "hanceville",
    region: "Alabama",
    tagline: "Hanceville, Alabama",
    heroImage: "/images/locations/hanceville-hero.webp",
  },
  {
    slug: "hartselle",
    region: "Alabama",
    tagline: "Hartselle, Alabama",
    heroImage: "/images/locations/hartselle-hero.webp",
  },
  {
    slug: "harvest",
    region: "Alabama",
    tagline: "Harvest, Alabama",
    heroImage: "/images/locations/harvest-hero.webp",
  },
  {
    slug: "hayneville",
    region: "Alabama",
    tagline: "Hayneville, Alabama",
    heroImage: "/images/locations/hayneville-hero.webp",
  },
  {
    slug: "hazel-green",
    region: "Alabama",
    tagline: "Hazel Green, Alabama",
    heroImage: "/images/locations/hazel-green-hero.webp",
  },
  {
    slug: "highland-home",
    region: "Alabama",
    tagline: "Highland Home, Alabama",
    heroImage: "/images/locations/highland-home-hero.webp",
  },
  {
    slug: "highland-lake",
    region: "Alabama",
    tagline: "Highland Lake, Alabama",
    heroImage: "/images/locations/highland-lake-hero.webp",
  },
  {
    slug: "hillsboro",
    region: "Alabama",
    tagline: "Hillsboro, Alabama",
    heroImage: "/images/locations/hillsboro-hero.webp",
  },
  {
    slug: "hokes-bluff",
    region: "Alabama",
    tagline: "Hokes Bluff, Alabama",
    heroImage: "/images/locations/hokes-bluff-hero.webp",
  },
  {
    slug: "hueytown",
    region: "Alabama",
    tagline: "Hueytown, Alabama",
    heroImage: "/images/locations/hueytown-hero.webp",
  },
  {
    slug: "irondale",
    region: "Alabama",
    tagline: "Irondale, Alabama",
    heroImage: "/images/locations/irondale-hero.webp",
  },
  {
    slug: "killen",
    region: "Alabama",
    tagline: "Killen, Alabama",
    heroImage: "/images/locations/killen-hero.webp",
  },
  {
    slug: "kimberly",
    region: "Alabama",
    tagline: "Kimberly, Alabama",
    heroImage: "/images/locations/kimberly-hero.webp",
  },
  {
    slug: "knoxville",
    region: "Alabama",
    tagline: "Knoxville, Alabama",
    heroImage: "/images/locations/knoxville-hero.webp",
  },
  {
    slug: "lanett",
    region: "Alabama",
    tagline: "Lanett, Alabama",
    heroImage: "/images/locations/lanett-hero.webp",
  },
  {
    slug: "leesburg",
    region: "Alabama",
    tagline: "Leesburg, Alabama",
    heroImage: "/images/locations/leesburg-hero.webp",
  },
  {
    slug: "leighton",
    region: "Alabama",
    tagline: "Leighton, Alabama",
    heroImage: "/images/locations/leighton-hero.webp",
  },
  {
    slug: "letohatchee",
    region: "Alabama",
    tagline: "Letohatchee, Alabama",
    heroImage: "/images/locations/letohatchee-hero.webp",
  },
  {
    slug: "lincoln",
    region: "Alabama",
    tagline: "Lincoln, Alabama",
    heroImage: "/images/locations/lincoln-hero.webp",
  },
  {
    slug: "loachapoka",
    region: "Alabama",
    tagline: "Loachapoka, Alabama",
    heroImage: "/images/locations/loachapoka-hero.webp",
  },
  {
    slug: "locust-fork",
    region: "Alabama",
    tagline: "Locust Fork, Alabama",
    heroImage: "/images/locations/locust-fork-hero.webp",
  },
  {
    slug: "lowndesboro",
    region: "Alabama",
    tagline: "Lowndesboro, Alabama",
    heroImage: "/images/locations/lowndesboro-hero.webp",
  },
  {
    slug: "loxley",
    region: "Alabama",
    tagline: "Loxley, Alabama",
    heroImage: "/images/locations/loxley-hero.webp",
  },
  {
    slug: "madison",
    region: "Alabama",
    tagline: "Madison, Alabama",
    heroImage: "/images/locations/madison-hero.webp",
  },
  {
    slug: "marbury",
    region: "Alabama",
    tagline: "Marbury, Alabama",
    heroImage: "/images/locations/marbury-hero.webp",
  },
  {
    slug: "mccalla",
    region: "Alabama",
    tagline: "McCalla, Alabama",
    heroImage: "/images/locations/mccalla-hero.webp",
  },
  {
    slug: "meadowbrook",
    region: "Alabama",
    tagline: "Meadowbrook, Alabama",
    heroImage: "/images/locations/meadowbrook-hero.webp",
  },
  {
    slug: "meridianville",
    region: "Alabama",
    tagline: "Meridianville, Alabama",
    heroImage: "/images/locations/meridianville-hero.webp",
  },
  {
    slug: "midfield",
    region: "Alabama",
    tagline: "Midfield, Alabama",
    heroImage: "/images/locations/midfield-hero.webp",
  },
  {
    slug: "midland-city",
    region: "Alabama",
    tagline: "Midland City, Alabama",
    heroImage: "/images/locations/midland-city-hero.webp",
  },
  {
    slug: "millbrook",
    region: "Alabama",
    tagline: "Millbrook, Alabama",
    heroImage: "/images/locations/millbrook-hero.webp",
  },
  {
    slug: "montevallo",
    region: "Alabama",
    tagline: "Montevallo, Alabama",
    heroImage: "/images/locations/montevallo-hero.webp",
  },
  {
    slug: "moss-point",
    region: "Alabama",
    tagline: "Moss Point, Alabama",
    heroImage: "/images/locations/moss-point-hero.webp",
  },
  {
    slug: "mount-olive",
    region: "Alabama",
    tagline: "Mount Olive, Alabama",
    heroImage: "/images/locations/mount-olive-hero.webp",
  },
  {
    slug: "mulga",
    region: "Alabama",
    tagline: "Mulga, Alabama",
    heroImage: "/images/locations/mulga-hero.webp",
  },
  {
    slug: "munford",
    region: "Alabama",
    tagline: "Munford, Alabama",
    heroImage: "/images/locations/munford-hero.webp",
  },
  {
    slug: "muscle-shoals",
    region: "Alabama",
    tagline: "Muscle Shoals, Alabama",
    heroImage: "/images/locations/muscle-shoals-hero.webp",
  },
  {
    slug: "new-market",
    region: "Alabama",
    tagline: "New Market, Alabama",
    heroImage: "/images/locations/new-market-hero.webp",
  },
  {
    slug: "newton",
    region: "Alabama",
    tagline: "Newton, Alabama",
    heroImage: "/images/locations/newton-hero.webp",
  },
  {
    slug: "newville",
    region: "Alabama",
    tagline: "Newville, Alabama",
    heroImage: "/images/locations/newville-hero.webp",
  },
  {
    slug: "notasulga",
    region: "Alabama",
    tagline: "Notasulga, Alabama",
    heroImage: "/images/locations/notasulga-hero.webp",
  },
  {
    slug: "odenville",
    region: "Alabama",
    tagline: "Odenville, Alabama",
    heroImage: "/images/locations/odenville-hero.webp",
  },
  {
    slug: "ohatchee",
    region: "Alabama",
    tagline: "Ohatchee, Alabama",
    heroImage: "/images/locations/ohatchee-hero.webp",
  },
  {
    slug: "opelika",
    region: "Alabama",
    tagline: "Opelika, Alabama",
    heroImage: "/images/locations/opelika-hero.webp",
  },
  {
    slug: "owens-cross-roads",
    region: "Alabama",
    tagline: "Owens Cross Roads, Alabama",
    heroImage: "/images/locations/owens-cross-roads-hero.webp",
  },
  {
    slug: "pansey",
    region: "Alabama",
    tagline: "Pansey, Alabama",
    heroImage: "/images/locations/pansey-hero.webp",
  },
  {
    slug: "pell-city",
    region: "Alabama",
    tagline: "Pell City, Alabama",
    heroImage: "/images/locations/pell-city-hero.webp",
  },
  {
    slug: "perdido",
    region: "Alabama",
    tagline: "Perdido, Alabama",
    heroImage: "/images/locations/perdido-hero.webp",
  },
  {
    slug: "pike-road",
    region: "Alabama",
    tagline: "Pike Road, Alabama",
    heroImage: "/images/locations/pike-road-hero.webp",
  },
  {
    slug: "pinckard",
    region: "Alabama",
    tagline: "Pinckard, Alabama",
    heroImage: "/images/locations/pinckard-hero.webp",
  },
  {
    slug: "pinson",
    region: "Alabama",
    tagline: "Pinson, Alabama",
    heroImage: "/images/locations/pinson-hero.webp",
  },
  {
    slug: "pleasant-grove",
    region: "Alabama",
    tagline: "Pleasant Grove, Alabama",
    heroImage: "/images/locations/pleasant-grove-hero.webp",
  },
  {
    slug: "prichard",
    region: "Alabama",
    tagline: "Prichard, Alabama",
    heroImage: "/images/locations/prichard-hero.webp",
  },
  {
    slug: "prospect",
    region: "Alabama",
    tagline: "Prospect, Alabama",
    heroImage: "/images/locations/prospect-hero.webp",
  },
  {
    slug: "ramer",
    region: "Alabama",
    tagline: "Ramer, Alabama",
    heroImage: "/images/locations/ramer-hero.webp",
  },
  {
    slug: "salem",
    region: "Alabama",
    tagline: "Salem, Alabama",
    heroImage: "/images/locations/salem-hero.webp",
  },
  {
    slug: "saraland",
    region: "Alabama",
    tagline: "Saraland, Alabama",
    heroImage: "/images/locations/saraland-hero.webp",
  },
  {
    slug: "satsuma",
    region: "Alabama",
    tagline: "Satsuma, Alabama",
    heroImage: "/images/locations/satsuma-hero.webp",
  },
  {
    slug: "scottsboro",
    region: "Alabama",
    tagline: "Scottsboro, Alabama",
    heroImage: "/images/locations/scottsboro-hero.webp",
  },
  {
    slug: "semmes",
    region: "Alabama",
    tagline: "Semmes, Alabama",
    heroImage: "/images/locations/semmes-hero.webp",
  },
  {
    slug: "sheffield",
    region: "Alabama",
    tagline: "Sheffield, Alabama",
    heroImage: "/images/locations/sheffield-hero.webp",
  },
  {
    slug: "shelby",
    region: "Alabama",
    tagline: "Shelby, Alabama",
    heroImage: "/images/locations/shelby-hero.webp",
  },
  {
    slug: "slocomb",
    region: "Alabama",
    tagline: "Slocomb, Alabama",
    heroImage: "/images/locations/slocomb-hero.webp",
  },
  {
    slug: "somerville",
    region: "Alabama",
    tagline: "Somerville, Alabama",
    heroImage: "/images/locations/somerville-hero.webp",
  },
  {
    slug: "spanish-fort",
    region: "Alabama",
    tagline: "Spanish Fort, Alabama",
    heroImage: "/images/locations/spanish-fort-hero.webp",
  },
  {
    slug: "springville",
    region: "Alabama",
    tagline: "Springville, Alabama",
    heroImage: "/images/locations/springville-hero.webp",
  },
  {
    slug: "steele",
    region: "Alabama",
    tagline: "Steele, Alabama",
    heroImage: "/images/locations/steele-hero.webp",
  },
  {
    slug: "sterrett",
    region: "Alabama",
    tagline: "Sterrett, Alabama",
    heroImage: "/images/locations/sterrett-hero.webp",
  },
  {
    slug: "stockton",
    region: "Alabama",
    tagline: "Stockton, Alabama",
    heroImage: "/images/locations/stockton-hero.webp",
  },
  {
    slug: "summerdale",
    region: "Alabama",
    tagline: "Summerdale, Alabama",
    heroImage: "/images/locations/summerdale-hero.webp",
  },
  {
    slug: "sylacauga",
    region: "Alabama",
    tagline: "Sylacauga, Alabama",
    heroImage: "/images/locations/sylacauga-hero.webp",
  },
  {
    slug: "sylvan-springs",
    region: "Alabama",
    tagline: "Sylvan Springs, Alabama",
    heroImage: "/images/locations/sylvan-springs-hero.webp",
  },
  {
    slug: "taft",
    region: "Alabama",
    tagline: "Taft, Alabama",
    heroImage: "/images/locations/taft-hero.webp",
  },
  {
    slug: "titus",
    region: "Alabama",
    tagline: "Titus, Alabama",
    heroImage: "/images/locations/titus-hero.webp",
  },
  {
    slug: "trafford",
    region: "Alabama",
    tagline: "Trafford, Alabama",
    heroImage: "/images/locations/trafford-hero.webp",
  },
  {
    slug: "trinity",
    region: "Alabama",
    tagline: "Trinity, Alabama",
    heroImage: "/images/locations/trinity-hero.webp",
  },
  {
    slug: "troy",
    region: "Alabama",
    tagline: "Troy, Alabama",
    heroImage: "/images/locations/troy-hero.webp",
  },
  {
    slug: "trussville",
    region: "Alabama",
    tagline: "Trussville, Alabama",
    heroImage: "/images/locations/trussville-hero.webp",
  },
  {
    slug: "tuscumbia",
    region: "Alabama",
    tagline: "Tuscumbia, Alabama",
    heroImage: "/images/locations/tuscumbia-hero.webp",
  },
  {
    slug: "tuskegee",
    region: "Alabama",
    tagline: "Tuskegee, Alabama",
    heroImage: "/images/locations/tuskegee-hero.webp",
  },
  {
    slug: "union-grove",
    region: "Alabama",
    tagline: "Union Grove, Alabama",
    heroImage: "/images/locations/union-grove-hero.webp",
  },
  {
    slug: "union-springs",
    region: "Alabama",
    tagline: "Union Springs, Alabama",
    heroImage: "/images/locations/union-springs-hero.webp",
  },
  {
    slug: "valhermoso-springs",
    region: "Alabama",
    tagline: "Valhermoso Springs, Alabama",
    heroImage: "/images/locations/valhermoso-springs-hero.webp",
  },
  {
    slug: "vance",
    region: "Alabama",
    tagline: "Vance, Alabama",
    heroImage: "/images/locations/vance-hero.webp",
  },
  {
    slug: "vestavia-hills",
    region: "Alabama",
    tagline: "Vestavia Hills, Alabama",
    heroImage: "/images/locations/vestavia-hills-hero.webp",
  },
  {
    slug: "warrior",
    region: "Alabama",
    tagline: "Warrior, Alabama",
    heroImage: "/images/locations/warrior-hero.webp",
  },
  {
    slug: "wellington",
    region: "Alabama",
    tagline: "Wellington, Alabama",
    heroImage: "/images/locations/wellington-hero.webp",
  },
  {
    slug: "west-blocton",
    region: "Alabama",
    tagline: "West Blocton, Alabama",
    heroImage: "/images/locations/west-blocton-hero.webp",
  },
  {
    slug: "westover",
    region: "Alabama",
    tagline: "Westover, Alabama",
    heroImage: "/images/locations/westover-hero.webp",
  },
  {
    slug: "wetumpka",
    region: "Alabama",
    tagline: "Wetumpka, Alabama",
    heroImage: "/images/locations/wetumpka-hero.webp",
  },
  {
    slug: "woodville",
    region: "Alabama",
    tagline: "Woodville, Alabama",
    heroImage: "/images/locations/woodville-hero.webp",
  },
]

export function getCityMeta(slug: string): CityMeta | undefined {
  return CITY_META.find((c) => c.slug === slug)
}
